version: "3.9"
services:
  crawler:
    env_file: .env

  shard:
    env_file: .env

  postgres:
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - flipance-db:/var/lib/postgresql/data

volumes:
  flipance-db: