apiVersion: v1
kind: ServiceAccount
metadata:
  name: flipance
  namespace: flipance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flipance
  name: flipance
rules:
- apiGroups:
  - apps
  - ""
  - batch/v1
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: flipance
  name: flipance-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flipance
subjects:
- kind: ServiceAccount
  namespace: flipance
  name: flipance