apiVersion: v1
kind: Service
metadata:
  name: flipance
  namespace: flipance
  labels: 
    group: db
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432