apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: flipance
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi